# Generated by Django 3.0.4 on 2020-03-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0002_auto_20200331_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='region',
            new_name='country',
        ),
    ]
